name: Deploy to ec2
on:
  push:
    branches:
      - main
jobs:
  ubuntu-jobs:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build and tag Docker image 
      run: |
        docker build -t  bolasanni/periodapp .
     
    - name: Log in to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
       docker push bolasanni/periodapp:latest
